import { Inter } from "next/font/google";
import "./globals.css";

import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight:['400', '600', '700'] });

import Header from "./components/header";
import Footer from "./components/Footer";

export const metadata = {
  title: "nextjs crash course",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="max-w-4xl mx-auto px-5">

       <Header />

        {children}
        <Footer />
        </div>
        
      </body>
    </html>
  );
}
